version: '3'

services:
  resume-shortlister:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./.streamlit:/app/.streamlit
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped